### ISSUE TITLE
[Feature Request] A command to pull canteen menus

### ISSUE THREAD

**Issue by hungdojan** [linuskmr/lunch-coordinator-bot#1]
Problem:
--
Even after deciding when to go to lunch, students do not know where to go to. I propose a new feature to display canteen information upon request.

Functionality:
--
Implement a series of `canteen` commands that will execute the following list of commands:
- `\ct_menu` - The bot will display a menu for the selected `canteen` and `date`.
- `\ct_oh` - Prints opening hours of the selected `canteen`.
- `\ct_src` - Send a canteen website link.

All commands that receive any parameters will have a button.

External Sources:
--
[Canteen menus](https://kanttiinit.fi) - webpage to pull data from
[Simple tutorial](https://medium.com/@mikez_dg/creating-a-simple-but-interactive-telegram-bot-with-python-a-complete-guide-d713f8b6c3d7)

**Comment by linuskmr** [comment]
Closed by #2
